/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoProductIdRouteImport } from './routes/catalogo.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoProductIdRoute = CatalogoProductIdRouteImport.update({
  id: '/catalogo/$productId',
  path: '/catalogo/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/catalogo': typeof CatalogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/conta' | '/favoritos' | '/catalogo/$productId' | '/catalogo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conta' | '/favoritos' | '/catalogo/$productId' | '/catalogo'
  id:
    | '__root__'
    | '/'
    | '/conta'
    | '/favoritos'
    | '/catalogo/$productId'
    | '/catalogo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaRoute: typeof ContaRoute
  FavoritosRoute: typeof FavoritosRoute
  CatalogoProductIdRoute: typeof CatalogoProductIdRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$productId': {
      id: '/catalogo/$productId'
      path: '/catalogo/$productId'
      fullPath: '/catalogo/$productId'
      preLoaderRoute: typeof CatalogoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaRoute: ContaRoute,
  FavoritosRoute: FavoritosRoute,
  CatalogoProductIdRoute: CatalogoProductIdRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
