/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ComentariosRouteImport } from './routes/comentarios'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAtividadesRouteImport } from './routes/admin.atividades'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminComentariosRouteImport } from './routes/admin.comentarios'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminFichasRouteImport } from './routes/admin.fichas'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminViagensRouteImport } from './routes/admin.viagens'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FichaTokenRouteImport } from './routes/ficha.$token'
import { Route as ViagensIndexRouteImport } from './routes/viagens.index'
import { Route as ViagensTripIdRouteImport } from './routes/viagens.$tripId'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ComentariosRoute = ComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtividadesRoute = AdminAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComentariosRoute = AdminComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFichasRoute = AdminFichasRouteImport.update({
  id: '/fichas',
  path: '/fichas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViagensRoute = AdminViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const FichaTokenRoute = FichaTokenRouteImport.update({
  id: '/ficha/$token',
  path: '/ficha/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensIndexRoute = ViagensIndexRouteImport.update({
  id: '/viagens/',
  path: '/viagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensTripIdRoute = ViagensTripIdRouteImport.update({
  id: '/viagens/$tripId',
  path: '/viagens/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/comentarios': typeof ComentariosRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/fichas': typeof AdminFichasRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ficha/$token': typeof FichaTokenRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/admin/': typeof AdminIndexRoute
  '/viagens/': typeof ViagensIndexRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/comentarios': typeof ComentariosRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/fichas': typeof AdminFichasRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ficha/$token': typeof FichaTokenRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/admin': typeof AdminIndexRoute
  '/viagens': typeof ViagensIndexRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/comentarios': typeof ComentariosRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/comentarios': typeof AdminComentariosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/fichas': typeof AdminFichasRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ficha/$token': typeof FichaTokenRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/admin/': typeof AdminIndexRoute
  '/viagens/': typeof ViagensIndexRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/calendario'
    | '/comentarios'
    | '/conta'
    | '/favoritos'
    | '/quem-somos'
    | '/admin/atividades'
    | '/admin/blog'
    | '/admin/comentarios'
    | '/admin/configuracoes'
    | '/admin/fichas'
    | '/admin/reservas'
    | '/admin/tags'
    | '/admin/viagens'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/ficha/$token'
    | '/viagens/$tripId'
    | '/admin/'
    | '/viagens/'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/calendario'
    | '/comentarios'
    | '/conta'
    | '/favoritos'
    | '/quem-somos'
    | '/admin/atividades'
    | '/admin/blog'
    | '/admin/comentarios'
    | '/admin/configuracoes'
    | '/admin/fichas'
    | '/admin/reservas'
    | '/admin/tags'
    | '/admin/viagens'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/ficha/$token'
    | '/viagens/$tripId'
    | '/admin'
    | '/viagens'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/calendario'
    | '/comentarios'
    | '/conta'
    | '/favoritos'
    | '/quem-somos'
    | '/admin/atividades'
    | '/admin/blog'
    | '/admin/comentarios'
    | '/admin/configuracoes'
    | '/admin/fichas'
    | '/admin/reservas'
    | '/admin/tags'
    | '/admin/viagens'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/ficha/$token'
    | '/viagens/$tripId'
    | '/admin/'
    | '/viagens/'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  ComentariosRoute: typeof ComentariosRoute
  ContaRoute: typeof ContaRoute
  FavoritosRoute: typeof FavoritosRoute
  QuemSomosRoute: typeof QuemSomosRoute
  FichaTokenRoute: typeof FichaTokenRoute
  ViagensTripIdRoute: typeof ViagensTripIdRoute
  ViagensIndexRoute: typeof ViagensIndexRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comentarios': {
      id: '/comentarios'
      path: '/comentarios'
      fullPath: '/comentarios'
      preLoaderRoute: typeof ComentariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atividades': {
      id: '/admin/atividades'
      path: '/atividades'
      fullPath: '/admin/atividades'
      preLoaderRoute: typeof AdminAtividadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comentarios': {
      id: '/admin/comentarios'
      path: '/comentarios'
      fullPath: '/admin/comentarios'
      preLoaderRoute: typeof AdminComentariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fichas': {
      id: '/admin/fichas'
      path: '/fichas'
      fullPath: '/admin/fichas'
      preLoaderRoute: typeof AdminFichasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/viagens': {
      id: '/admin/viagens'
      path: '/viagens'
      fullPath: '/admin/viagens'
      preLoaderRoute: typeof AdminViagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/ficha/$token': {
      id: '/ficha/$token'
      path: '/ficha/$token'
      fullPath: '/ficha/$token'
      preLoaderRoute: typeof FichaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/': {
      id: '/viagens/'
      path: '/viagens'
      fullPath: '/viagens/'
      preLoaderRoute: typeof ViagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/$tripId': {
      id: '/viagens/$tripId'
      path: '/viagens/$tripId'
      fullPath: '/viagens/$tripId'
      preLoaderRoute: typeof ViagensTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAtividadesRoute: typeof AdminAtividadesRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminComentariosRoute: typeof AdminComentariosRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFichasRoute: typeof AdminFichasRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminViagensRoute: typeof AdminViagensRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAtividadesRoute: AdminAtividadesRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminComentariosRoute: AdminComentariosRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFichasRoute: AdminFichasRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminViagensRoute: AdminViagensRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  ComentariosRoute: ComentariosRoute,
  ContaRoute: ContaRoute,
  FavoritosRoute: FavoritosRoute,
  QuemSomosRoute: QuemSomosRoute,
  FichaTokenRoute: FichaTokenRoute,
  ViagensTripIdRoute: ViagensTripIdRoute,
  ViagensIndexRoute: ViagensIndexRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
