/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminViagensRouteImport } from './routes/admin.viagens'
import { Route as ViagensIndexRouteImport } from './routes/viagens.index'
import { Route as ViagensTripIdRouteImport } from './routes/viagens.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViagensRoute = AdminViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AdminRoute,
} as any)
const ViagensIndexRoute = ViagensIndexRouteImport.update({
  id: '/viagens/',
  path: '/viagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensTripIdRoute = ViagensTripIdRouteImport.update({
  id: '/viagens/$tripId',
  path: '/viagens/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/admin/': typeof AdminIndexRoute
  '/viagens/': typeof ViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/admin': typeof AdminIndexRoute
  '/viagens': typeof ViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/admin/': typeof AdminIndexRoute
  '/viagens/': typeof ViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/conta'
    | '/favoritos'
    | '/admin/configuracoes'
    | '/admin/reservas'
    | '/admin/viagens'
    | '/viagens/$tripId'
    | '/admin/'
    | '/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta'
    | '/favoritos'
    | '/admin/configuracoes'
    | '/admin/reservas'
    | '/admin/viagens'
    | '/viagens/$tripId'
    | '/admin'
    | '/viagens'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/conta'
    | '/favoritos'
    | '/admin/configuracoes'
    | '/admin/reservas'
    | '/admin/viagens'
    | '/viagens/$tripId'
    | '/admin/'
    | '/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContaRoute: typeof ContaRoute
  FavoritosRoute: typeof FavoritosRoute
  ViagensTripIdRoute: typeof ViagensTripIdRoute
  ViagensIndexRoute: typeof ViagensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/viagens': {
      id: '/admin/viagens'
      path: '/viagens'
      fullPath: '/admin/viagens'
      preLoaderRoute: typeof AdminViagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/viagens/': {
      id: '/viagens/'
      path: '/viagens'
      fullPath: '/viagens/'
      preLoaderRoute: typeof ViagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/$tripId': {
      id: '/viagens/$tripId'
      path: '/viagens/$tripId'
      fullPath: '/viagens/$tripId'
      preLoaderRoute: typeof ViagensTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminViagensRoute: typeof AdminViagensRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminViagensRoute: AdminViagensRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContaRoute: ContaRoute,
  FavoritosRoute: FavoritosRoute,
  ViagensTripIdRoute: ViagensTripIdRoute,
  ViagensIndexRoute: ViagensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
